export const PRODUCT_FETCH_REQUEST = "PRODUCT_FETCH_REQUEST";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAILURE = "PRODUCT_FETCH_FAILURE";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FORM_CART = "REMOVE_FORM_CART";
export const CHECKOUT = "CHECKOUT";
